{{- if .Values.component.ingress }}
{{- $envAll := . }}

---
{{- if semverCompare "<1.19.0" (include "cubefs.kubernetes.version" .) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: cubefs-ingress
spec:
  rules:
{{- if semverCompare "<1.19.0" (include "cubefs.kubernetes.version" .) }}
  {{- if .Values.component.master }}
    - host: {{ .Values.master.host }}
      http:
        paths:
          - backend:
              serviceName: master-service
              servicePort: {{ .Values.master.port }}
  {{- end }}
  {{- if .Values.component.monitor }}
    - host: {{ .Values.grafana.host }}
      http:
        paths:
          - backend:
              serviceName: grafana-service
              servicePort: {{ .Values.grafana.port }}
  {{- end }}
  {{- if .Values.component.objectnode }}
    - host: {{ .Values.objectnode.host }}
      http:
        paths:
          - backend:
              serviceName: objectnode-service
              servicePort: {{ .Values.objectnode.port }}
  {{- end }}
{{- else }}
  {{- if .Values.component.master }}
    - host: {{ .Values.master.host }}
      http:
        paths:
          - backend:
              service:
                name: master-service
                port:
                  number: {{ .Values.master.port }}
            path: /
            pathType: Prefix
  {{- end }}
  {{- if .Values.component.monitor }}
    - host: {{ .Values.grafana.host }}
      http:
        paths:
          - backend:
              service:
                name: grafana-service
                port:
                  number: {{ .Values.grafana.port }}
            path: /
            pathType: Prefix
  {{- end }}
  {{- if .Values.component.objectnode }}
    - host: {{ .Values.objectnode.host }}
      http:
        paths:
          - backend:
              service:
                name: objectnode-service
                port:
                  number: {{ .Values.objectnode.port }}
            path: /
            pathType: Prefix
  {{- end }}
{{- end }}
{{ end }}
